name: Build Docusaurus

on: 
  push:
    branches: ["master", "main"]

permissions:
  checks: write
  contents: write

jobs:
  build-docusaurus:
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          path: 'docusaurus'
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Docusaurus
        run: |
          cd docusaurus
          npm install
      - name: Build Docusaurus
        run: |
          cd docusaurus
          rm -rf build
          npm run docusaurus clear
          rm -f build.tar
          npm run build
          tar cf build.tar -C build --transform 's~^\./~~' .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
              name: build
              path: docusaurus/build.tar
              retention-days: 90
        
