name: Build Docusaurus

on: 
  pull_request:
  push:
    branches: ["master", "main"]

jobs:
  build-docusaurus:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup Workspace'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          path: 'repo'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install Docusaurus
        run: |
          npx create-docusaurus@latest docusaurus classic -s 
          cp -Rf repo/. docusaurus/
          cd docusaurus
          npm i docusaurus-lunr-search --save
          npm install
          npm run swizzle docusaurus-lunr-search SearchBar -- --eject --danger
      - name: Build Docusaurus
        run: |
          cd docusaurus
          npm run build
          tar cf build.tar -C build --transform 's~^\./~~' .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with: 
              name: build
              path: docusaurus/build.tar
              retention-days: 14
        
